FROM linuxserver/code-server:4.16.1

RUN sudo apt update
RUN sudo apt install software-properties-common -y
RUN sudo add-apt-repository 'ppa:deadsnakes/ppa'
RUN sudo apt install python3.11 -y

RUN sudo apt install virtualenv -y
